### ISSUE TITLE
~ Expansion in path

### ISSUE THREAD

**Issue by Johan37** [Jakob37/Ogi#1]
I encountered this problem when tying to run setup on a new Windows machine using Cygwin. If you use ~ in your path for a new data folder like `~/ogi-logs`  it is treated as a relative path and expanded like this:  `/home/<user>/~/ogi-logs` instead of the expected behavior of  `/home/<user>/ogi-logs`

Log:
```
$ ogi/ogi.py setup

Please provide the directory where your Ogi data should be stored. If you are planning on using
Ogi on multiple devices, it is recommendedto specify a synced folder, such as a Dropbox-folder.
Save path: ~/ogi-logs
/home/<user>/~/ogi-logs, is that correct? [Y/n] n
No path provided, try again

```

**Comment by Jakob37** [comment]
Thank you for this comment! (I didn't see it until now). I will add this to my list of Windows-support-features. It will not be present in the coming release v0.2.0, could hopefully be added to the sequential release.

I appreciated this pull request, so if you encounter any other issues - Keep them coming :)

**Comment by Jakob37** [comment]
I have decided to close this issue, as the alternative of writing out the absolute path is simple enough. Thank you for the input!
