### ISSUE TITLE
Error when trying to setup

### ISSUE THREAD

**Issue by ghost** [Jakob37/Ogi#2]
I get this error when trying to run the initial setup using "ogi setup" on my Arch Linux computer: 

Traceback (most recent call last):
  File "./ogi", line 196, in <module>
    parse_arguments()
  File "./ogi", line 35, in parse_arguments
    parse_log(subparsers)
  File "./ogi", line 76, in parse_log
    conf = ogi_config.get_config()
  File "/home/danalm/git/Ogi/ogi_config.py", line 76, in get_config
    .format(conf_path))
Exception: Config file not found at expected path: /home/danalm/git/Ogi/ogi.conf, run setup command (ogi.py setup) to get started

Steps to reproduce:
- Clone repository 
- cd into folder
- run "./ogi setup"

I have python 3 installed.

**Comment by Jakob37** [comment]
Alright, I really need to run through the setup part. This issue should be resolved now, though there is a follow-up issue with the database setup which I will look into later today.

**Comment by Jakob37** [comment]
Thanks for the issue message! You are living dangerously on the master-branch, but I will try to keep it more stable in the future.

**Comment by Jakob37** [comment]
Now the second issue is fixed too - The setup should work fine now.
